### ISSUE TITLE
Warning on ubunto 20.04, Noetic

### ISSUE THREAD

**Issue by MF-Ahmed** [JulioPlaced/active_graph_slam#2]
Hello!
I am getting the following warning  after roslaunch graph_d_exploration graph_dopt.launch 

[INFO] [1672932885.792008, 75.930000]: /filter: Filter is waiting for the map.
[INFO] [1672932886.291723, 76.430000]: /filter: Filter is waiting for the map.
I have edited the paths in 
graph_d_exploration/param/mapping_karto_g2o.yaml and graph_d_exploration/scripts/constants.py 
maybe I need to download a seperate g2o graph file?
Thanks

**Comment by JulioPlaced** [comment]
Can you copy the files content and check if the .g2o is being saved in the directory you specified?

**Comment by MF-Ahmed** [comment]
Thanks, yes a .g2o file is being saved in specified in the specified location but its empty.
There are my paths  

for graph_d_exploration/param/mapping_karto_g2o.yaml 
graph_dir: /home/usr/data/git/active_graph_slam/graph.g2o

& for graph_d_exploration/scripts/constants.py
GRAPH_PATH_ = "/home/usr/git/active_graph_slam/graph.g2o"

which saved the .g2o file in /home/usr/data/git/active_graph_slam

I think the filter.py cannot find the .g2o file to read, perhaps I need to download a .g2o map file separately

**Comment by JulioPlaced** [comment]
The path must be the same in the two files. Otherwise the .g2o file that the SLAM module saves will not be found by the decision maker module.

**Comment by MF-Ahmed** [comment]
Now both the files have the same path as 
"/home/usr/data/git/active_graph_slam/map/graphh.g2o" --> constants.py
/home/usr/data/git/active_graph_slam/map/graphh.g2o --> mapping_karto_g2o.yaml
the .g2o file is created in 
/home/usr/data/git/active_graph_slam/map/graphh.g2o
but its empty!
and the same warning appears
INFO] [1673018053.547489, 24.020000]: /filter: Filter is waiting for the map.

**Comment by JulioPlaced** [comment]
I assume that you cannot see the laser scan in Rviz (nor the gridmap thus). In that case it is probably related to your GPU compatibility with Gazebo/ROS gpu_ray plugin. Try the following:

- Go to .../active_graph_slam/src/graph_d_exploration/launch/include/urdf folder
- Edit kobuki_gazebo.urdf as follows, 
   - Comment line 199 (`<!-- <sensor type="gpu_ray" name="head_hokuyo_sensor">-->`) and uncomment line 200 (`<sensor type="ray" name="head_hokuyo_sensor">`). 
   - Do the same with 228 (`<!--<plugin name="gazebo_ros_head_hokuyo_controller" filename="libgazebo_ros_gpu_laser.so">-->`) and 229 (`<plugin name="gazebo_ros_head_hokuyo_controller" filename="libgazebo_ros_laser.so">`)

This way you will be using CPU instead.

**Comment by MF-Ahmed** [comment]
ok I modified the file, now everything is  working fine.
Thanks  a lot
