### ISSUE TITLE
 Question about the validation folder

### ISSUE THREAD

**Issue by MF-Ahmed** [JulioPlaced/active_graph_slam#3]
Hi Julio,
I am a little curious about how did you compute the FRH_P_toro_opt_edges.txt and  FRH_P_toro_opt_nodes.txt files?
Thanks

**Comment by JulioPlaced** [comment]
Hello! 
Those files are computed from the .g2o/.toro graphs from the datasets mentioned in the paper. Just a format conversion. The *_edges.txt contains the edge information and *_nodes.txt the node information of the pose-graphs. 
Also, *_opt files are the graphs after perfoming a graph optimization (I used Ceres for that if I remember correctly)

**Comment by MF-Ahmed** [comment]
Thanks for your answer. Just another maybe too naive question, Is there any way to quantify the uncertainty on the fly during the graph SLAM process other than computing the D-Optimality for every edge pair?

**Comment by JulioPlaced** [comment]
I think that you need to compute optimality criteria (e.g., D-opt) for every pair and then metric of the graph (e.g., the number of spanning trees for D-opt). But this should be extremely fast.

**Comment by MF-Ahmed** [comment]
Thanks, So it can be D-optimality of an edge / No. spanning trees for the whole pose-graph?

**Comment by JulioPlaced** [comment]
Yes, any of the relationships described in here https://ieeexplore.ieee.org/abstract/document/10003990 will work (eq. 32-35)

**Comment by MF-Ahmed** [comment]
Thanks a lot

**Comment by MF-Ahmed** [comment]
Hi 
Regarding the utils.py  in def build_fullFIM(graph) why is the final FIM returned as diff = A - A.T?
Thanks

**Comment by JulioPlaced** [comment]
[That function returns A.](https://github.com/JulioPlaced/active_graph_slam/blob/main/src/validation/utils.py#L122) 
The condition you mention is to check for symmetry.

**Comment by MF-Ahmed** [comment]
Thanks, things are more clear now.
Regarding  https://ieeexplore.ieee.org/abstract/document/10003990 when going from eq. 18 to eq.19 can you elaborate the  exp (AdAB)  = A exp (B)A−1 (exponent of the adjoint operator on lie groups elements A and B) expression as I could not find it in https://arxiv.org/abs/1812.01537
Thanks

**Comment by JulioPlaced** [comment]
You can actually find that definition in the document you mentioned ([A micro Lie theory for state estimation in robotics](https://arxiv.org/abs/1812.01537)). More specifically, at the top of page 7, see the equation blocks before eq. (29).

**Comment by MF-Ahmed** [comment]
Thanks

**Comment by MF-Ahmed** [comment]
Hi
Regarding https://ieeexplore.ieee.org/abstract/document/10003990 in eq. (19) shouldn't the second Adjoint in the exponential be  $Ad_{T^{-1}_{wk}}d_{wk}^{^}$ instead of being  $Ad_{T^{-1}_{wi}}d_{wk}^{^}$ ?
Thanks

**Comment by JulioPlaced** [comment]
Not sure what you are referring to, equation (19) reads:
T_wi = exp(d_wi^) \bar{T}_wi

**Comment by MF-Ahmed** [comment]
Hi
can you specify the format of FRH_P_toro_edges.txt
each line represents an edge measurement  the  format should be
from_edge    to_edge   x  y  theta   Q_11   Q_12   Q_13   Q_22   Q_23   Q_33  
which are 11 elements but the file actually has 12 elements in each line  
Thanks

**Comment by JulioPlaced** [comment]
The information is as follows:

- id. 1,
- id. 2,
- type of constraint (odometry 0, loop closure 1),
- relative transformation (3 elements), 
- FIM associated to it (6 elements).

**Comment by MF-Ahmed** [comment]
Thanks, 
for "type of constraint",  how did you extract it form the  FRH_P_toro.graph file, if its the case  
I have the .g2o pose graph file and am trying to exttract the *_edges.txt  and *_nodes.txt

**Comment by JulioPlaced** [comment]
There are many ways to do so, the following is a simple one:
Odometry constraints are usually between adjacent and consecutive nodes. On the other hand, loop closure constraints are between non-consecutive nodes and also node1Id > node2Id.
You can use this to determine whether a given constraint is a loop closure or an odometry constraint.
For example, you can enforce odometry constraints for consecutive edges (e.g., 1->2, 2->3) and loop closure constraints  between non-consecutive edges with Id2>Id1 (e.g., 3->1).

**Comment by MF-Ahmed** [comment]
Thanks Le 22 mai 2023 11:32, "Julio A. Placed" ***@***.***> a écrit :
There are many ways to do so, the following is a simple one:
Odometry constraints are usually between adjacent and consecutive nodes. On the other hand, loop closure constraints are between non-consecutive nodes and also node1Id > node2Id.
You can use this to determine whether a given constraint is a loop closure or an odometry constraint.
For example, you can enforce that odometry constraints for consecutive edges (e.g., 1->2, 2->3) and loop closure constraints are between non-consecutive edges with Id2>Id1 (e.g., 3->1).
