### ISSUE TITLE
Question about D-opt definition in the RAL-2022 reference

### ISSUE THREAD

**Issue by bairuofei** [JulioPlaced/active_graph_slam#4]
Hi, in your paper "A General Relationship between Optimality Criteria and Connectivity Indices for Active Graph-SLAM. IEEE Robotics and Automation Letters", the definition of D-opt(Y) is based on the (non-reduced) Laplacian matrix, as shown in the following. 

![image](https://github.com/JulioPlaced/active_graph_slam/assets/41278025/c0a15c70-3bd2-4161-8f49-90220e61ce6b)

Here t(G) is obtained by the determinant of the reduced Laplacian matrix, and then times $n$ to approximate the determinant of non-reduced Laplacian matrix. 

However, this does not follow the original definition of D-opt. The D-opt should be defined over a non-singular matrix, otherwise the D-opt will be zero. 

Although it is ok for just notation, the problem will occur when comparing the D-opt of two pose graphs. If we assume the numbers of nodes are $n_1$ and $n_2$ respectively, then following your definition, the D-opt should be:
$D-opt(Y_1) = (n_1 t(G_1))^{\frac{1}{n_1}}$ and $D-opt(Y_2) = (n_2 t(G_2))^{\frac{1}{n_2}}$.
If using the reduced Laplacian matrix, the D-opt should be:
$D-opt(Y_1) = (t(G_1))^{\frac{1}{n_1 - 1}}$ and $D-opt(Y_2) = (t(G_2))^{\frac{1}{n_2 - 1}}$.

Obviously, the two types of formulations are not equivalent when comparing the D-opt of two pose graphs. May I know how you consider this problem?

**Comment by JulioPlaced** [comment]
Hello, 
Thank you for the interest. 
The (n-1) term you mention is considered in the formulation, that is why, e.g., in equation 30 the exponent (n-1)/n appears. 
In the formulation you propose, I believe that a couple terms are missing, perhaps you mixed the traditional and modern formulations of D-optimality?
I am closing this issue as it is not directly related to the code, but I am definitely happy to continue this discussion. Please write me at jplaced@unizar.es if you want.
