### ISSUE TITLE
How to get the ground truth trajectory of the robot?

### ISSUE THREAD

**Issue by bairuofei** [JulioPlaced/active_graph_slam#5]
Hi, may I know how to get the ground truth trajectory for the robot, so that I can evaluate the accuracy of the pose graph optimization? I implement this by subscribing to the `gazebo_msgs::ModelStates` topic， but it seems to have some delay compared with the robot's real-time position. Is there any existing API to save the ground truth trajectory in this repo? Thank you.

**Comment by JulioPlaced** [comment]
You can access to ground-truth data by subscribing to Gazebo robot states. I believe this is a question related to Gazebo rather than this repo.
