### ISSUE TITLE
Error: Frontier callback failed due to dimension mismatch of -1. Skipping callback.

### ISSUE THREAD

**Issue by bairuofei** [JulioPlaced/active_graph_slam#6]
Hi, when I run the simulation following the instructions in the README.md file, the console frequently outputs the following error messages. May I know whether this is a normal case or if I made some mistakes?

```shell
[ERROR] [1690542736.008621, 3037.420000]: Frontier callback failed due to dimension mismatch of -1. Skipping callback.
[ERROR] [1690542687.454126, 2988.870000]: Frontier callback failed due to dimension mismatch of 3. Skipping callback.
[ERROR] [1690542764.075796, 3065.480000]: /assigner: No points in plan to frontier at [-14.25797939 -14.60626411]. Probably a high potential area!!
```

[](url)
![2023-07-28_19-06](https://github.com/JulioPlaced/active_graph_slam/assets/41278025/159e223e-fde1-49e5-a38d-6d160e051bec)

**Comment by JulioPlaced** [comment]
Hello, that occurs when the filter that removes old frontier points cannot find a correspondence between a frontier and its associated time stamp. As long as it occurs sparsely, there is no issue with that output.
