### ISSUE TITLE
Index Error

### ISSUE THREAD

**Issue by bairuofei** [JulioPlaced/active_graph_slam#7]
https://github.com/JulioPlaced/active_graph_slam/blob/b1e0b8db35e078fdcf56c8000202480a54d622dc/src/graph_d_exploration/scripts/functions.py#L217C5-L217C5

Here
```py
return [100, Data[int(index)]][int(index) < len(Data)]
```

Should be:

```py
if int(index) < len(Data):
    return Data[int(index)]
return 100
```

**Comment by JulioPlaced** [comment]
The first code snippet you provided does the following, using a list comprehension technique:
- If the index is less than the length of Data, it returns Data[int(index)],
- otherwise, it returns 100.

Both expressions do the same and there is no index error.
Closing.

**Comment by bairuofei** [comment]
It seems the first code will cause an index error because when constructing `[100, Data[int(index)]]`, it already uses `int(index)` as the index of `Data`. If `int(index)` is no less than the length of `Data` then there will be an index error. I encountered this error when running the code.
